module.exports = {
    printWidth: 80,
    tabWidth: 2,
    useTabs: true,
    semi: false,
    singleQuote: true,
    quoteProps: "as-needsd",
    jsxSingleQuote: true,
    trailingComma: "none",
    bracketSpacing: true,
    jsxBracketSameLine: false,
    arrowParens: "always",
    rangeStart: 0,
    rangeEnd: Infinity,
    requirePragma: false,
    insertPragma: false,
    proseWrap: "preserve",
    htmlWhitespaceSensitivity: "css",
    endOfLine: "lf"
  };