export enum CalendarActions {
  SET_CALENDAR_MONTH = "SET_CALENDAR_MONTH",
  SET_CALENDAR_MONTH_INDEX = "SET_CALENDAR_MONTH_INDEX",
  SET_SMALL_CALENDAR_MONTH_INDEX = "SET_SMALL_CALENDAR_MONTH_INDEX"
};
  