export enum AuthActions{
    SET_AUTH = 'SET_AUTH',
    SET_IS_LOADING = 'SET_IS_LOADING',
    SET_LOGIN_USER = 'SET_LOGIN_USER',
    LOGOUT_USER = 'LOGOUT_USER',
    SET_REGISTRATION_USER = 'SET_REGISTRATION_USER',
    VERIFY_SESSION = 'VERIFY_SESSION'
}